In [10]:
import numpy as np

random_value=np.random.randint(100,size=(10,3))
print(random_value)

[[ 3 88 11]
 [55 73 40]
 [31 27 35]
 [ 3 36 85]
 [80 19 88]
 [99 35 54]
 [79 73 94]
 [80 28 86]
 [24 15 19]
 [69 25 40]]
