In [1]:
import numpy as np

random_value=np.random.randint(100,size=(10,3))
print(random_value)

[[98 57 58]
 [90 88 12]
 [18 57 43]
 [ 7 30 98]
 [39 66  8]
 [50 27  3]
 [38 27 34]
 [98  6 57]
 [84 14 17]
 [69  8  3]]
