In [5]:
import numpy as np

random_value=np.random.randint(100,size=(10,3))
print(random_value)

[[ 3 62 60]
 [12 74 82]
 [92 70 73]
 [17 41 27]
 [27 75 78]
 [ 3 41 83]
 [50  0 80]
 [12 96 18]
 [31 67 25]
 [60 23  6]]
